teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
<<<<<<< HEAD
=======
    deadman_buttons: [4]
>>>>>>> 2cec3cf795ed33f495b8eeb585037e90a0d9ca93
    axis_mappings:
      -
        axis: 1
        target: linear.x
<<<<<<< HEAD
        scale: 1.0
      -
        axis: 2
        target: angular.z
        scale: 1.0

  joy_priority:
    type: action
    action_name: joy_priority_action 
    buttons: [0]

  joy_turbo_decrease:
    type: action
    action_name: joy_turbo_decrease
    buttons: [1, 4, 5]

  joy_turbo_increase:
    type: action
    action_name: joy_turbo_increase
    buttons: [3, 4, 5]
=======
        scale: 0.3
      -
        axis: 0
        target: angular.z
        scale: 0.5
>>>>>>> 2cec3cf795ed33f495b8eeb585037e90a0d9ca93

  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: home
      reach_time:
        secs: 3
    buttons: [8, 1]

  arms_t:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: arms_t
      reach_time:
        secs: 3
    buttons: [8, 0]

  hands_down:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: hands_down
      reach_time:
        secs: 3
<<<<<<< HEAD
    buttons: [8, 2]
=======
    buttons: [8, 2]
>>>>>>> 2cec3cf795ed33f495b8eeb585037e90a0d9ca93
