teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.3
      -
        axis: 2
        target: angular.z
        scale: 0.5

  joy_priority:
    type: action
    action_name: joy_priority_action 
    buttons: [0]

  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: home
      reach_time:
        secs: 3
    buttons: [8, 1]

  arms_t:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: arms_t
      reach_time:
        secs: 3
    buttons: [8, 0]

  hands_down:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: hands_down
      reach_time:
        secs: 3
    buttons: [8, 2]
