play_motion:
  motions:
    arms_t:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.707, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
          0.707, 0.0, 0.1, 0.0, 0.0, 0.0]
        time_from_start: 0.0
    hands_down:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, -0.4, 0.25, -0.1, 0.6109, 0.0, 0.0, 0.0, -0.4,
          0.25, -0.1, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 0.0
    home:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
