both_arms_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_joints
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  joint_trajectory_action_node:
    joints: *arm_joints
    constraints:
      goal_time: 0.6
      arm_right_1_joint:
        goal: 0.02
      arm_right_2_joint:
        goal: 0.02
      arm_right_3_joint:
        goal: 0.02
      arm_right_4_joint:
        goal: 0.02
      arm_right_5_joint:
        goal: 0.02
      arm_right_6_joint:
        goal: 0.02
      arm_right_7_joint:
        goal: 0.02
      arm_left_1_joint:
        goal: 0.02
      arm_left_2_joint:
        goal: 0.02
      arm_left_3_joint:
        goal: 0.02
      arm_left_4_joint:
        goal: 0.02
      arm_left_5_joint:
        goal: 0.02
      arm_left_6_joint:
        goal: 0.02
      arm_left_7_joint:
        goal: 0.02